###
POST http://localhost:3000/api/wilders HTTP/1.1
content-type: application/json

{
    "name":"Laura",
    "city": "Saint-Etienne",
    "skills":[
        {"title":"angular", "votes":5},
        {"title":"php", "votes":12}
    ]
}

###
GET http://127.0.0.1:3000/api/wilders


###
PUT http://127.0.0.1:3000/api/wilders/6227ad5dc5fd45b22a05b26d 
content-type: application/json

{
    "city": "Saint-Etienne",
}


###
DELETE  http://127.0.0.1:3000/localhost:3000/api/wilders/62285a2efd76050a181215ba HTTP/1.1





